### ISSUE TITLE
table is not responsive after using this tool

### ISSUE THREAD

**Issue by Jetxiaoli** [DmitriiSer/angular2-collapsible#1]
I see table https://dmitriiser.github.io/angular2-collapsible-example/ is responsive, but when I used it, responsive is interrupted. 
when using <table class="table table-hover">, responsive is ok.
<collapsible-table class="table table-hover" [type]="accordion" [striped]="true" [select] = "true">

**Comment by DmitriiSer** [comment]
Can you provide a piece of your code that I could look at? In my [example]( https://dmitriiser.github.io/angular2-collapsible-example/) the table is not responsive, this feature is not yet implemented.

**Comment by DmitriiSer** [comment]
Closing for now since there wasn't any activity.
