### ISSUE TITLE
How to get the expand status of the "collapsible-list-item"??

### ISSUE THREAD

**Issue by sshyamprasath** [DmitriiSer/angular2-collapsible#2]
I would like to show right and down arrow while the item collapse and expand respectively. Is there any option or property to identify the status of each "collapsible-list-item"??. 

If then we can use that for displaying appropriate icon inside the header.

**Comment by mephasor** [comment]
I second that one : )

**Comment by DmitriiSer** [comment]
I will look into this in more detail

**Comment by DmitriiSer** [comment]
Implemented in version 0.0.44.
