### ISSUE TITLE
Not compatible to Angular 6

### ISSUE THREAD

**Issue by volkantas** [DmitriiSer/angular2-collapsible#7]
Library not work with angular 6

**Comment by RZR666** [comment]
collapsible-event-service

import { Observable } from 'rxjs/Rx';

change to

import { Observable } from 'rxjs';

index.js

import { Subject } from 'rxjs/Rx';

change to

import { Subject } from 'rxjs';

**Comment by miteshngandhi** [comment]
For the benefit of the larger audience, can you please update the component and publish it?

**Comment by DmitriiSer** [comment]
Sorry guys it took so long. I finally was able to find some time to resolve this issue. Please find a new release that is compatible with Angular 6 [here](https://github.com/DmitriiSer/angular2-collapsible/releases/tag/v0.6.1) or on [npmjs.com](https://www.npmjs.com/package/angular2-collapsible)
